"""Task 73 (issue #73): the privacy audit's own cross-boundary seam tests.

Every one of the four boundaries the issue names (camera, credentials,
prompts, drafts) already has dedicated, individually-passing coverage
elsewhere in this repo -- `tests/test_ai_provider_key_and_logging_safety.py`
(Task 45), `tests/test_edit_session_draft_sync_api.py` (Task 43),
`tests/test_public_gallery_api.py`/`tests/test_project_publish_api.py`
(Tasks 49/50), `tests/test_thumbnails.py`/`tests/test_project_thumbnail_api.py`
(Task 54). What none of those exercise is the *combination*: one project,
walked end to end through a real AI create-scene call, a real Accept, a
real draft, and a real publish -- then scanned for whether anything
private leaked once every one of those individually-correct features
started interacting on the same project. That is exactly the "seams
between features" gap this task's own issue calls out.

This file drives that single full flow through Django's real test client
(no mocked views, only the AI provider itself is faked -- exactly like
every other AI test in this repo) and scans:

- Every HTTP response body collected along the way (create-scene,
  accept-proposal, draft upsert, publish, public detail, public gallery
  list, public thumbnail bytes).
- Every log record emitted during the whole flow (`caplog`, capturing
  every logger, not just `ai_provider`).

...for three distinctive, never-otherwise-occurring markers: a fake but
API-key-shaped `MISTRAL_API_KEY` value, the raw AI prompt text, and a
draft's own distinctive scene content. None of the three should appear
anywhere in that combined haystack.
"""

from __future__ import annotations

import copy
import json
import logging
from pathlib import Path

import pytest
from django.contrib.auth import get_user_model
from django.core.cache import cache
from rest_framework.test import APIClient

import scenes.ai_api as ai_api
from ai_provider.fake_provider import FakeAIProviderScenario, FakeAISceneProvider
from scenes.models import EditSessionDraft, Project

BLANK_SCENE = json.loads(
    (
        Path(__file__).resolve().parent.parent / "schema" / "fixtures" / "valid" / "blank.json"
    ).read_text()
)

# Distinctive, never-otherwise-occurring markers -- chosen to be
# implausible substrings of anything legitimately generated by this
# codebase (a UUID, a username, a scene id), so a match is unambiguous
# evidence of a real leak, not a coincidental collision.
DISTINCTIVE_API_KEY = "sk-AUDIT73-MISTRAL-SECRET-KEY-7f2c9e6b1a"
DISTINCTIVE_PROMPT = (
    "AUDIT73-PROMPT-MARKER: a bioluminescent jellyfish garden that pulses with the beat"
)
DISTINCTIVE_DRAFT_MARKER = "audit73-draft-secret-scene-id-marker"


@pytest.fixture(autouse=True)
def _clear_cache():
    cache.clear()
    yield
    cache.clear()


@pytest.fixture
def owner(db):
    return get_user_model().objects.create_user(username="audit73_owner")


@pytest.fixture
def owner_client(owner):
    client = APIClient()
    client.force_authenticate(owner)
    return client


@pytest.fixture
def anon_client():
    return APIClient()


@pytest.fixture
def project(owner):
    return Project.objects.create(owner=owner)


def _bodies_contain(bodies: list[str], marker: str) -> bool:
    return any(marker in body for body in bodies)


@pytest.mark.django_db
def test_full_ai_draft_publish_flow_never_leaks_key_prompt_or_draft_content(
    monkeypatch, owner_client, anon_client, project, caplog
):
    # A distinctive, API-key-shaped value in the environment -- if any code
    # path along this flow ever read and echoed/logged `MISTRAL_API_KEY`
    # (even by accident, e.g. through a debug repr or an overly broad log
    # statement), it would show up as this exact string. The AI endpoints
    # below are wired to a fake provider (matching every other AI test in
    # this repo), so this key is never actually needed for a successful
    # call -- its only purpose here is as a tripwire.
    monkeypatch.setenv("MISTRAL_API_KEY", DISTINCTIVE_API_KEY)

    fake_provider = FakeAISceneProvider(FakeAIProviderScenario.SUCCESS)
    monkeypatch.setattr(ai_api, "get_ai_provider", lambda: fake_provider)

    caplog.set_level(logging.DEBUG)

    response_bodies: list[str] = []

    def _record(response) -> None:
        # Not every response has a JSON/text body (e.g. the raw PNG
        # thumbnail) -- capture what's decodable as text and always
        # capture the raw bytes too via .content.decode(errors="replace")
        # so a PNG byte stream containing a leaked marker (implausible,
        # but the whole point of an audit is not assuming) is still
        # scanned.
        response_bodies.append(response.content.decode("utf-8", errors="replace"))

    # --- 1. AI create-scene with a distinctive prompt -----------------
    create_response = owner_client.post(
        f"/api/projects/{project.public_id}/ai/create-scene/",
        {"prompt": DISTINCTIVE_PROMPT},
        format="json",
    )
    assert create_response.status_code == 200
    _record(create_response)
    scene_json = create_response.json()["scene"]

    # --- 2. Accept the proposal -> a real SceneVersion -----------------
    accept_response = owner_client.post(
        f"/api/projects/{project.public_id}/ai/accept-proposal/",
        {
            "operation": "ai_create",
            "scene_json": scene_json,
            "base_version_id": None,
            "change_label": "",
        },
        format="json",
    )
    assert accept_response.status_code == 201
    _record(accept_response)

    # --- 3. A draft with distinctive content, on the same project -----
    draft_scene = copy.deepcopy(BLANK_SCENE)
    draft_scene["id"] = DISTINCTIVE_DRAFT_MARKER
    draft_response = owner_client.put(
        f"/api/projects/{project.public_id}/draft/audit73-session/",
        {"draft_json": draft_scene, "client_seq": 1},
        format="json",
    )
    assert draft_response.status_code == 200
    _record(draft_response)

    # --- 4. Publish (requires meaningful metadata first) ---------------
    owner_client.patch(
        f"/api/projects/{project.public_id}/",
        {"title": "Audit 73 flow project", "description": "A real description."},
        format="json",
    )
    publish_response = owner_client.post(f"/api/projects/{project.public_id}/publish/")
    assert publish_response.status_code == 200
    _record(publish_response)

    # --- 5. Every public-facing surface, hit anonymously ---------------
    public_detail_response = anon_client.get(f"/api/public/projects/{project.public_id}/")
    assert public_detail_response.status_code == 200
    _record(public_detail_response)

    gallery_response = anon_client.get("/api/public/projects/")
    assert gallery_response.status_code == 200
    _record(gallery_response)

    thumbnail_response = anon_client.get(f"/api/public/projects/{project.public_id}/thumbnail.png")
    assert thumbnail_response.status_code == 200
    _record(thumbnail_response)

    # --- 6. Also re-read the draft and the owner's own version history,
    # since those are legitimately owner-reachable and this audit is
    # about *unintended* boundaries, not proving the owner can't see
    # their own data -- but the API key and the raw prompt should still
    # never appear even there. ---
    draft_read_response = owner_client.get(
        f"/api/projects/{project.public_id}/draft/audit73-session/"
    )
    assert draft_read_response.status_code == 200
    _record(draft_read_response)

    history_response = owner_client.get(f"/api/projects/{project.public_id}/versions/")
    assert history_response.status_code == 200
    _record(history_response)

    # --- Evidence: scan every collected response body -------------------
    assert not _bodies_contain(response_bodies, DISTINCTIVE_API_KEY), (
        "Provider API key leaked into an HTTP response body somewhere in the "
        "AI create -> accept -> draft -> publish -> public-read flow."
    )
    assert not _bodies_contain(response_bodies, DISTINCTIVE_PROMPT), (
        "Raw AI prompt text leaked into an HTTP response body -- the prompt is "
        "never supposed to be echoed back or persisted anywhere but the "
        "original create-scene request itself."
    )
    # The draft marker legitimately appears in the two owner-authorized
    # draft responses (steps 3 and 6) -- excluded from this scan by
    # construction: it must never appear in the publish/public-facing
    # bodies specifically.
    public_facing_bodies = response_bodies[3:6]  # publish, public detail, gallery
    assert not _bodies_contain(public_facing_bodies, DISTINCTIVE_DRAFT_MARKER), (
        "Draft content leaked into a publish/public-facing response body."
    )
    assert DISTINCTIVE_DRAFT_MARKER not in thumbnail_response.content.decode("latin-1"), (
        "Draft content leaked into the generated thumbnail PNG bytes."
    )

    # --- Evidence: scan every log record emitted during the whole flow --
    log_text = "\n".join(record.getMessage() for record in caplog.records)
    # Also scan each record's `extra`-attached structured payload
    # (`ai_provider.logging.log_operation_result` attaches `extra={"ai_provider": record}`)
    # since `getMessage()` alone only covers the format string/args, not
    # arbitrary extra attributes a handler might render.
    extra_text = "\n".join(
        json.dumps(vars(record).get("ai_provider"), default=str)
        for record in caplog.records
        if hasattr(record, "ai_provider")
    )
    full_log_text = log_text + "\n" + extra_text

    assert DISTINCTIVE_API_KEY not in full_log_text, (
        "Provider API key leaked into application logs."
    )
    assert DISTINCTIVE_PROMPT not in full_log_text, (
        "Raw AI prompt text leaked into application logs under the default no-retention policy."
    )
    assert DISTINCTIVE_DRAFT_MARKER not in full_log_text, (
        "Draft content leaked into application logs."
    )


@pytest.mark.django_db
def test_draft_is_never_reachable_by_a_different_user_even_after_publish(
    monkeypatch, owner, project
):
    """A companion, narrower seam check: publishing a project (a public-facing
    action) must never change who can read its private draft -- authorization
    is per-user/per-project, not conditioned on visibility. Uses the real
    permission-checked endpoint, not a direct model query, so this proves the
    actual reachable behavior through the API.
    """
    other_user = get_user_model().objects.create_user(username="audit73_other")
    other_client = APIClient()
    other_client.force_authenticate(other_user)

    owner_client = APIClient()
    owner_client.force_authenticate(owner)

    draft_scene = copy.deepcopy(BLANK_SCENE)
    draft_scene["id"] = DISTINCTIVE_DRAFT_MARKER
    owner_client.put(
        f"/api/projects/{project.public_id}/draft/audit73-session/",
        {"draft_json": draft_scene, "client_seq": 1},
        format="json",
    )
    assert EditSessionDraft.objects.filter(project=project, user=owner).exists()

    # Publish the project (owner-only metadata + publish dance).
    owner_client.patch(
        f"/api/projects/{project.public_id}/",
        {"title": "Reachability check", "description": "A description."},
        format="json",
    )
    owner_client.post(f"/api/projects/{project.public_id}/publish/")

    # A different authenticated user still cannot reach the draft.
    other_response = other_client.get(f"/api/projects/{project.public_id}/draft/audit73-session/")
    assert other_response.status_code == 404
