"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlsplit

from django.core.exceptions import ImproperlyConfigured

from backend.admin_identities import parse_admin_identities
from backend.database import parse_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def get_required_env(name: str) -> str:
    """Return a required environment variable, or fail loudly and clearly.

    Required settings (secrets and PostgreSQL connection details) must be
    supplied via the environment rather than defaulted in code. See
    `.env.example` for the full list of variables this project uses and
    `AGENTS.md` for the copyable setup commands, including how to load a
    local `.env` file with `uv run --env-file .env ...`.
    """
    try:
        return os.environ[name]
    except KeyError:
        raise ImproperlyConfigured(
            f"Required environment variable '{name}' is not set. "
            "Copy .env.example to .env, fill in a real value, and load it "
            "into the environment (e.g. `uv run --env-file .env python "
            "manage.py runserver`). See AGENTS.md for details."
        ) from None


def get_bool_env(name: str, default: bool) -> bool:
    """Return an optional boolean environment variable."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def get_csrf_trusted_origins() -> list[str]:
    """Read explicit browser origins allowed to make unsafe same-site requests.

    Django requires CSRF trusted origins to include a scheme.  Rejecting
    malformed values here avoids accidentally turning a hostname list or a
    wildcard into a broader trust rule.
    """
    origins = []
    configured_origins = os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000,http://localhost:5000,http://127.0.0.1:5000",
    ).split(",")
    configured_origins.extend(["https://animate.creatrweb.com", "https://creatrweb.replit.app"])
    if DEBUG:
        # Vite is the browser-facing local server, so its origin—not Django's
        # internal :8000 origin—appears in a real form POST's Origin header.
        configured_origins.extend(["http://localhost:5000", "http://127.0.0.1:5000"])
    for raw_origin in configured_origins:
        origin = raw_origin.strip()
        if not origin:
            continue
        parsed = urlsplit(origin)
        try:
            port = parsed.port
        except ValueError:
            port = None
        if (
            parsed.scheme.lower() not in {"http", "https"}
            or not parsed.hostname
            or parsed.username is not None
            or parsed.password is not None
            or parsed.path not in {"", "/"}
            or parsed.query
            or parsed.fragment
            or "*" in parsed.netloc
            or port is None
            and ":" in parsed.netloc.rsplit("]", 1)[-1]
        ):
            raise ImproperlyConfigured(
                "CSRF_TRUSTED_ORIGINS must contain only fully qualified "
                "http(s) origins such as https://animate.creatrweb.com."
            )
        origins.append(f"{parsed.scheme.lower()}://{parsed.netloc.lower()}")
    return origins


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_required_env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = get_csrf_trusted_origins()

# Replit's HTTPS edge forwards requests through Vite to Django on localhost.
# Trust the edge's forwarding headers so Django/allauth builds callback URLs
# using the browser-visible HTTPS host instead of the internal :8000 address.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Deployment security is enabled automatically whenever DEBUG is off. Each
# flag remains overridable so an operator can make the policy explicit in
# environment configuration, but production refuses unsafe combinations.
SECURE_SSL_REDIRECT = get_bool_env("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = get_bool_env("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = get_bool_env("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
try:
    SECURE_HSTS_SECONDS = int(
        os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0")
    )
except ValueError:
    raise ImproperlyConfigured(
        "DJANGO_SECURE_HSTS_SECONDS must be a whole number of seconds."
    ) from None
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool_env(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG
)
SECURE_HSTS_PRELOAD = get_bool_env("DJANGO_SECURE_HSTS_PRELOAD", default=not DEBUG)

if not DEBUG:
    if not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "Production requires DJANGO_ALLOWED_HOSTS with explicit hostnames; "
            "wildcards are not allowed."
        )
    if not SECURE_SSL_REDIRECT:
        raise ImproperlyConfigured("Production requires DJANGO_SECURE_SSL_REDIRECT=True.")
    if not SESSION_COOKIE_SECURE or not CSRF_COOKIE_SECURE:
        raise ImproperlyConfigured(
            "Production requires secure session and CSRF cookies "
            "(DJANGO_SESSION_COOKIE_SECURE=True and "
            "DJANGO_CSRF_COOKIE_SECURE=True)."
        )
    if SECURE_HSTS_SECONDS <= 0:
        raise ImproperlyConfigured(
            "Production requires an explicitly reviewed positive DJANGO_SECURE_HSTS_SECONDS value."
        )
elif SECURE_HSTS_SECONDS < 0:
    raise ImproperlyConfigured("DJANGO_SECURE_HSTS_SECONDS cannot be negative.")

# PostgreSQL connection, supplied as a single `DATABASE_URL` (Replit's
# convention for its managed PostgreSQL databases: a development Repl and
# a deployed production environment each get their own URL, injected as
# an environment variable — Django only ever reads the one it's given).
# Required and validated at settings-load time, so a missing or malformed
# value fails fast with a clear message. See `docs/plan.md`'s "Database
# deployment boundary" section and AGENTS.md for the full picture.
DATABASE_URL = get_required_env('DATABASE_URL')

# AI quota and rate-limit state must be shared by every production worker.
# Django's database cache uses the configured PostgreSQL database and needs no
# additional service or dependency. Development and test settings retain the
# deterministic process-local default; production refuses to fall back to it.
CACHES: dict[str, dict[str, object]]
if DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "gesture-reactive-studio-dev",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "backend.database_cache.AtomicDatabaseCache",
            "LOCATION": "django_cache",
            "TIMEOUT": None,
        }
    }

# Google OAuth (Task 12). Required and validated at settings-load time,
# like every other secret here. Real values are provisioned per Task 75;
# until then this fails fast with a clear message just like a missing
# DJANGO_SECRET_KEY would, and backend/backend/test_settings.py supplies safe
# placeholder values so the offline test suite doesn't need real
# credentials. See AGENTS.md and .env.example.
GOOGLE_OAUTH_CLIENT_ID = get_required_env('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = get_required_env('GOOGLE_OAUTH_CLIENT_SECRET')

# GitHub OAuth (issue #420) is optional: unlike Google, it is not required
# for the site to function, so it is off by default and enabled only when
# both variables are explicitly set. Setting only one is a malformed
# configuration and fails fast, just like a missing required variable
# would, rather than silently starting with a half-configured provider.
GITHUB_OAUTH_CLIENT_ID = os.environ.get('GITHUB_OAUTH_CLIENT_ID', '').strip()
GITHUB_OAUTH_CLIENT_SECRET = os.environ.get('GITHUB_OAUTH_CLIENT_SECRET', '').strip()
if bool(GITHUB_OAUTH_CLIENT_ID) != bool(GITHUB_OAUTH_CLIENT_SECRET):
    raise ImproperlyConfigured(
        "GITHUB_OAUTH_CLIENT_ID and GITHUB_OAUTH_CLIENT_SECRET must either both "
        "be set (to enable GitHub sign-in) or both be left unset (to keep it "
        "disabled). Only one of the two is currently set."
    )
GITHUB_OAUTH_ENABLED = bool(GITHUB_OAUTH_CLIENT_ID and GITHUB_OAUTH_CLIENT_SECRET)

# PayPal subscription billing (issue #424) is optional, same all-or-none
# pattern as GitHub above: PAYPAL_CLIENT_ID/PAYPAL_CLIENT_SECRET/
# PAYPAL_WEBHOOK_ID must all be set together to enable it, or all left
# unset to keep it disabled (the webhook endpoint 404s -- see
# scenes.paypal_gate, mirroring backend.oauth_gates). No merchant
# credentials are required to engineer or test this service -- see #445.
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', '').strip()
PAYPAL_CLIENT_SECRET = os.environ.get('PAYPAL_CLIENT_SECRET', '').strip()
PAYPAL_WEBHOOK_ID = os.environ.get('PAYPAL_WEBHOOK_ID', '').strip()
_paypal_fields_set = [bool(PAYPAL_CLIENT_ID), bool(PAYPAL_CLIENT_SECRET), bool(PAYPAL_WEBHOOK_ID)]
if any(_paypal_fields_set) and not all(_paypal_fields_set):
    raise ImproperlyConfigured(
        "PAYPAL_CLIENT_ID, PAYPAL_CLIENT_SECRET, and PAYPAL_WEBHOOK_ID must either "
        "all be set (to enable PayPal billing) or all be left unset (to keep it "
        "disabled). Only some of the three are currently set."
    )
PAYPAL_ENABLED = all(_paypal_fields_set)
# "sandbox" (default) or "live" -- which PayPal API base URL the real
# adapter (scenes/paypal_adapter.py) calls.
PAYPAL_MODE = os.environ.get('PAYPAL_MODE', 'sandbox').strip()
if PAYPAL_MODE not in ('sandbox', 'live'):
    raise ImproperlyConfigured("PAYPAL_MODE must be 'sandbox' or 'live'.")

# Environment-configured application-admin identities (issue #421). Empty by
# default (grants nobody). See backend.admin_identities for the finite
# `email:`/`username:` syntax and scenes.management.commands
# .reconcile_admin_identities for how this becomes a persisted grant.
ADMIN_IDENTITIES = parse_admin_identities(os.environ.get('ADMIN_IDENTITIES', ''))

# Root key used only to encrypt user-owned Mistral credentials. Keep this in
# deployment configuration and rotate it deliberately (rotation invalidates
# existing encrypted credentials unless they are re-encrypted during a
# controlled migration).
MISTRAL_CREDENTIAL_ENCRYPTION_KEY = get_required_env('MISTRAL_CREDENTIAL_ENCRYPTION_KEY')
MISTRAL_CREDENTIAL_PREVIOUS_ENCRYPTION_KEYS = [
    key.strip()
    for key in os.environ.get('MISTRAL_CREDENTIAL_PREVIOUS_ENCRYPTION_KEYS', '').split(',')
    if key.strip()
]

# Signup protection is opt-in for development. If enabled, production must
# provide every verification setting; it must never silently accept signups.
RECAPTCHA_ENABLED = get_bool_env("RECAPTCHA_ENABLED", default=False)
RECAPTCHA_SITE_KEY = os.environ.get("RECAPTCHA_SITE_KEY", "")
RECAPTCHA_SECRET_KEY = os.environ.get("RECAPTCHA_SECRET_KEY", "")
RECAPTCHA_ACTION = os.environ.get("RECAPTCHA_ACTION", "signup")
RECAPTCHA_MIN_SCORE = float(os.environ.get("RECAPTCHA_MIN_SCORE", "0.5"))
RECAPTCHA_ALLOWED_HOSTNAMES = {
    host.strip()
    for host in os.environ.get("RECAPTCHA_ALLOWED_HOSTNAMES", "").split(",")
    if host.strip()
}
RECAPTCHA_VERIFY_URL = "https://www.google.com/recaptcha/api/siteverify"
RECAPTCHA_TIMEOUT_SECONDS = 5
if (
    RECAPTCHA_ENABLED
    and not DEBUG
    and (not RECAPTCHA_SITE_KEY or not RECAPTCHA_SECRET_KEY or not RECAPTCHA_ALLOWED_HOSTNAMES)
):
    raise ImproperlyConfigured(
        "RECAPTCHA_ENABLED requires RECAPTCHA_SITE_KEY, RECAPTCHA_SECRET_KEY, "
        "and RECAPTCHA_ALLOWED_HOSTNAMES in production."
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'scenes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Task 66/issue #66: registered unconditionally, but a complete no-op
    # unless AI_PROVIDER=fake is set in this process's environment (see
    # ai_provider/config.py's use_fake_ai_provider and
    # ai_provider/e2e_scenario.py) -- lets the Playwright AI/recovery
    # end-to-end suite select a deterministic AI outcome per request via
    # the X-E2E-AI-Scenario header, with zero effect on any real
    # deployment (no documented .env sets AI_PROVIDER).
    'ai_provider.e2e_scenario.E2EScenarioMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Google sign-in only in V1 (see docs/plan.md), minimal identity scopes
# only (no Drive/Calendar/etc access), authorization-code flow with PKCE
# (access_type "online": no offline refresh token, since we don't need
# ongoing Google API access after sign-in).
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_OAUTH_CLIENT_ID,
            'secret': GOOGLE_OAUTH_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['openid', 'email', 'profile'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
    },
}
if GITHUB_OAUTH_ENABLED:
    # GitHub's own minimal-scope equivalent: `user:email` reads the
    # account's (possibly private) verified email address, with no other
    # GitHub API access. Omitting this key entirely (the disabled case)
    # leaves the provider unconfigured — see backend.oauth_gates, which
    # gates the login/callback routes closed regardless.
    SOCIALACCOUNT_PROVIDERS['github'] = {
        'APP': {
            'client_id': GITHUB_OAUTH_CLIENT_ID,
            'secret': GITHUB_OAUTH_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['user:email'],
    }

# Google already verifies the account's email before we ever see it.
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_FORMS = {'signup': 'backend.forms.RecaptchaSignupForm'}
# V1 supports Google (required) and GitHub (optional, environment-gated)
# sign-in only. Both providers verify the email during their OAuth flow,
# while the local allauth signup route remains present only to show a
# clear policy message to old bookmarks and to avoid contradictory account
# copy.
ACCOUNT_ADAPTER = "backend.account_adapter.SocialOnlySignupAccountAdapter"
SOCIALACCOUNT_ADAPTER = "backend.social_account_adapter.LinkedProvidersSocialAccountAdapter"
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backend.context_processors.recaptcha',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': parse_database_url(DATABASE_URL),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email. Development intentionally prints messages locally. Production uses
# SMTP by default; operators may select another deliberate backend through
# EMAIL_BACKEND rather than silently inheriting the development console.
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
    if not DEBUG
    else "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
try:
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
except ValueError:
    raise ImproperlyConfigured("EMAIL_PORT must be a whole number.") from None
EMAIL_USE_TLS = get_bool_env("EMAIL_USE_TLS", default=not DEBUG)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")

if not DEBUG and EMAIL_BACKEND in {
    "django.core.mail.backends.console.EmailBackend",
    "django.core.mail.backends.locmem.EmailBackend",
    "django.core.mail.backends.dummy.EmailBackend",
}:
    raise ImproperlyConfigured(
        "Production EMAIL_BACKEND must deliver mail; console, locmem, and "
        "dummy backends are development/test-only."
    )


# Logging. Django's own default LOGGING config only sends the
# 'django.request' logger's unhandled-exception tracebacks to console
# when DEBUG=True (its 'console' handler is filtered by
# RequireDebugTrue) -- in production the traceback's only other
# destination is emailing ADMINS, which this project doesn't set, so it
# silently goes nowhere. Issue #240: this made an unhandled 500 in
# production (#238) completely invisible in Replit's own log capture,
# even though the request-summary line (from the separate
# 'django.server' logger, never filtered by DEBUG) was visible.
# Adding a dedicated, unfiltered handler for 'django.request' fixes
# that without touching DEBUG, ADMINS, or any other production-safety
# setting -- 'propagate: True' keeps the existing mail_admins behavior
# (still a no-op with no ADMINS configured, unchanged from before)
# alongside this new console output.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "django_request_console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["django_request_console"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}
