# Generated by Django 6.1 on 2026-08-16 07:32

import django.db.models.deletion
import scenes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_postgres_invariants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('project_created', 'Project created'), ('metadata_updated', 'Metadata updated'), ('version_saved', 'Version saved'), ('version_restored', 'Version restored'), ('version_deleted', 'Version deleted'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('forked', 'Forked'), ('ai_proposal_accepted', 'AI proposal accepted'), ('ai_proposal_rejected', 'AI proposal rejected'), ('exported', 'Exported')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activity', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='scenes.project')),
            ],
            options={
                'verbose_name_plural': 'project activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditSessionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('draft_json', models.JSONField()),
                ('last_autosaved_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=scenes.models.default_draft_expiry)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='scenes.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_session_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_autosaved_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user', 'session_id'), name='unique_draft_scope')],
            },
        ),
    ]
