# Generated by Django 6.1 on 2026-08-17 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0008_project_creation_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
