# Generated by Django 6.1 on 2026-08-18 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0013_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['visibility', '-published_at', '-id'], name='project_public_gallery_idx'),
        ),
    ]
