# Generated by Django 6.1 on 2026-08-30 02:28

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0019_sceneversion3d_ai_request_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project3d',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='project3d',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='project3d',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project3d',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
