# Generated by Django 6.1 on 2026-08-30 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0020_alter_project3d_options_alter_project3d_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
                ('content_type', models.CharField(default='image/png', max_length=50)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('scene_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='scenes.sceneversion3d')),
            ],
        ),
    ]
