"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlsplit

from django.core.exceptions import ImproperlyConfigured

from config.database import parse_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def get_required_env(name: str) -> str:
    """Return a required environment variable, or fail loudly and clearly.

    Required settings (secrets and PostgreSQL connection details) must be
    supplied via the environment rather than defaulted in code. See
    `.env.example` for the full list of variables this project uses and
    `AGENTS.md` for the copyable setup commands, including how to load a
    local `.env` file with `uv run --env-file .env ...`.
    """
    try:
        return os.environ[name]
    except KeyError:
        raise ImproperlyConfigured(
            f"Required environment variable '{name}' is not set. "
            "Copy .env.example to .env, fill in a real value, and load it "
            "into the environment (e.g. `uv run --env-file .env python "
            "manage.py runserver`). See AGENTS.md for details."
        ) from None


def get_bool_env(name: str, default: bool) -> bool:
    """Return an optional boolean environment variable."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def get_csrf_trusted_origins() -> list[str]:
    """Read explicit browser origins allowed to make unsafe same-site requests.

    Django requires CSRF trusted origins to include a scheme.  Rejecting
    malformed values here avoids accidentally turning a hostname list or a
    wildcard into a broader trust rule.
    """
    origins = []
    configured_origins = os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000",
    ).split(",")
    configured_origins.extend(
        ["https://animate.creatrweb.com", "https://creatrweb.replit.app"]
    )
    for raw_origin in configured_origins:
        origin = raw_origin.strip()
        if not origin:
            continue
        parsed = urlsplit(origin)
        try:
            port = parsed.port
        except ValueError:
            port = None
        if (
            parsed.scheme.lower() not in {"http", "https"}
            or not parsed.hostname
            or parsed.username is not None
            or parsed.password is not None
            or parsed.path not in {"", "/"}
            or parsed.query
            or parsed.fragment
            or "*" in parsed.netloc
            or port is None
            and ":" in parsed.netloc.rsplit("]", 1)[-1]
        ):
            raise ImproperlyConfigured(
                "CSRF_TRUSTED_ORIGINS must contain only fully qualified "
                "http(s) origins such as https://animate.creatweb.com."
            )
        origins.append(f"{parsed.scheme.lower()}://{parsed.netloc.lower()}")
    return origins


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_required_env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = get_csrf_trusted_origins()

# Replit's HTTPS edge forwards requests through Vite to Django on localhost.
# Trust the edge's forwarding headers so Django/allauth builds callback URLs
# using the browser-visible HTTPS host instead of the internal :8000 address.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# PostgreSQL connection, supplied as a single `DATABASE_URL` (Replit's
# convention for its managed PostgreSQL databases: a development Repl and
# a deployed production environment each get their own URL, injected as
# an environment variable — Django only ever reads the one it's given).
# Required and validated at settings-load time, so a missing or malformed
# value fails fast with a clear message. See `_docs/plan.md`'s "Database
# deployment boundary" section and AGENTS.md for the full picture.
DATABASE_URL = get_required_env('DATABASE_URL')

# Google OAuth (Task 12). Required and validated at settings-load time,
# like every other secret here. Real values are provisioned per Task 75;
# until then this fails fast with a clear message just like a missing
# DJANGO_SECRET_KEY would, and config/test_settings.py supplies safe
# placeholder values so the offline test suite doesn't need real
# credentials. See AGENTS.md and .env.example.
GOOGLE_OAUTH_CLIENT_ID = get_required_env('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = get_required_env('GOOGLE_OAUTH_CLIENT_SECRET')

# Root key used only to encrypt user-owned Mistral credentials. Keep this in
# deployment configuration and rotate it deliberately (rotation invalidates
# existing encrypted credentials unless they are re-encrypted during a
# controlled migration).
MISTRAL_CREDENTIAL_ENCRYPTION_KEY = get_required_env('MISTRAL_CREDENTIAL_ENCRYPTION_KEY')
MISTRAL_CREDENTIAL_PREVIOUS_ENCRYPTION_KEYS = [
    key.strip()
    for key in os.environ.get('MISTRAL_CREDENTIAL_PREVIOUS_ENCRYPTION_KEYS', '').split(',')
    if key.strip()
]

# Signup protection is opt-in for development. If enabled, production must
# provide every verification setting; it must never silently accept signups.
RECAPTCHA_ENABLED = get_bool_env("RECAPTCHA_ENABLED", default=False)
RECAPTCHA_SITE_KEY = os.environ.get("RECAPTCHA_SITE_KEY", "")
RECAPTCHA_SECRET_KEY = os.environ.get("RECAPTCHA_SECRET_KEY", "")
RECAPTCHA_ACTION = os.environ.get("RECAPTCHA_ACTION", "signup")
RECAPTCHA_MIN_SCORE = float(os.environ.get("RECAPTCHA_MIN_SCORE", "0.5"))
RECAPTCHA_ALLOWED_HOSTNAMES = {
    host.strip()
    for host in os.environ.get("RECAPTCHA_ALLOWED_HOSTNAMES", "").split(",")
    if host.strip()
}
RECAPTCHA_VERIFY_URL = "https://www.google.com/recaptcha/api/siteverify"
RECAPTCHA_TIMEOUT_SECONDS = 5
if (
    RECAPTCHA_ENABLED
    and not DEBUG
    and (not RECAPTCHA_SITE_KEY or not RECAPTCHA_SECRET_KEY or not RECAPTCHA_ALLOWED_HOSTNAMES)
):
    raise ImproperlyConfigured(
        "RECAPTCHA_ENABLED requires RECAPTCHA_SITE_KEY, RECAPTCHA_SECRET_KEY, "
        "and RECAPTCHA_ALLOWED_HOSTNAMES in production."
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'scenes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Task 66/issue #66: registered unconditionally, but a complete no-op
    # unless AI_PROVIDER=fake is set in this process's environment (see
    # ai_provider/config.py's use_fake_ai_provider and
    # ai_provider/e2e_scenario.py) -- lets the Playwright AI/recovery
    # end-to-end suite select a deterministic AI outcome per request via
    # the X-E2E-AI-Scenario header, with zero effect on any real
    # deployment (no documented .env sets AI_PROVIDER).
    'ai_provider.e2e_scenario.E2EScenarioMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Google sign-in only in V1 (see _docs/plan.md), minimal identity scopes
# only (no Drive/Calendar/etc access), authorization-code flow with PKCE
# (access_type "online": no offline refresh token, since we don't need
# ongoing Google API access after sign-in).
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_OAUTH_CLIENT_ID,
            'secret': GOOGLE_OAUTH_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['openid', 'email', 'profile'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
    },
}

# Google already verifies the account's email before we ever see it.
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_FORMS = {"signup": "config.forms.RecaptchaSignupForm"}
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.recaptcha',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': parse_database_url(DATABASE_URL),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
