import {
  getMediaBlob,
  getProject,
  listMediaAssetsForProject,
  listScenesForProject,
  listPieceVersions,
  type LocalPieceVersionRecord,
  type LocalMediaAssetRecord,
} from './localProjectRepository';

export type LocalPiecePackageModule = {
  buildPiecePackage: (input: {
    kind: '2d';
    title: string;
    description: string;
    appVersion: string;
    records: Array<{ schemaVersion: number; data: Record<string, unknown> }>;
    mediaAssets: Array<{
      sourceAssetId?: string;
      filename: string;
      altText: string;
      mimeType: string;
      bytes: Uint8Array;
    }>;
  }) => Promise<Uint8Array>;
  parsePiecePackage: (bytes: Uint8Array) => Promise<unknown>;
};

async function loadPiecePackageModule(): Promise<LocalPiecePackageModule> {
  return import('./piecePackage');
}

export type LocalPiecePackageResult = {
  bytes: Uint8Array;
  /** UTF-8 bytes of serialized piece/version records, excluding package overhead. */
  pieceBytes: number;
  /** Bytes of the media blobs included in the package, counted once each. */
  mediaBytes: number;
  /** Number of media blobs included in the package. */
  mediaFiles: number;
  missingAssets: LocalMediaAssetRecord[];
};

export type LocalPiecePackageMeasurement = {
  pieceBytes: number;
  mediaBytes: number;
  mediaFiles: number;
  missingAssets: LocalMediaAssetRecord[];
};

/**
 * Measure expanded stored content for quota preflight. Record data is stored
 * as JSON payloads in the package; schema metadata, the ZIP manifest, and
 * archive/container bytes are transport overhead and do not count here.
 */
export function measureLocalPiecePackageContent(
  records: Array<{ data: Record<string, unknown> }>,
  mediaByteSizes: readonly number[],
): { pieceBytes: number; mediaBytes: number; mediaFiles: number } {
  const encoder = new TextEncoder();
  const pieceBytes = records.reduce(
    (total, record) => total + encoder.encode(JSON.stringify(record.data)).byteLength,
    0,
  );
  const mediaBytes = mediaByteSizes.reduce((total, byteSize) => total + byteSize, 0);
  return { pieceBytes, mediaBytes, mediaFiles: mediaByteSizes.length };
}

// Portable packages carry descriptions but intentionally omit local thumbnail
// blobs; thumbnails are derived and regenerated by the receiving UI.

type LoadedPieceContent = {
  project: NonNullable<Awaited<ReturnType<typeof getProject>>>;
  kind: '2d' | '3d' | 'generated';
  records: Array<{ schemaVersion: number; data: Record<string, unknown> }>;
  mediaAssets: Array<{
    sourceAssetId: string;
    filename: string;
    altText: string;
    mimeType: string;
    bytes?: Uint8Array;
  }>;
  missingAssets: LocalMediaAssetRecord[];
  measurement: Omit<LocalPiecePackageMeasurement, 'missingAssets'>;
  latest: Record<string, unknown>;
};

async function loadLocalPieceContent(
  db: IDBDatabase,
  ownerId: string,
  projectId: string,
  options: { includeMediaBytes: boolean; kind?: '2d' | '3d' | 'generated' },
): Promise<LoadedPieceContent> {
  const project = await getProject(db, ownerId, projectId);
  if (!project) throw new Error('The local piece is missing or belongs to another owner.');
  const kind = options.kind ?? project.kind ?? '2d';
  const assets = await listMediaAssetsForProject(db, projectId);
  const mediaAssets: LoadedPieceContent['mediaAssets'] = [];
  const mediaByteSizes: number[] = [];
  const missingAssets: LocalMediaAssetRecord[] = [];
  for (const asset of assets) {
    const blob = await getMediaBlob(db, asset.id);
    if (!blob) {
      missingAssets.push(asset);
      continue;
    }
    mediaByteSizes.push(blob.size);
    mediaAssets.push({
      sourceAssetId: asset.id,
      filename: asset.filename,
      altText: asset.altText,
      mimeType: asset.mimeType,
      ...(options.includeMediaBytes ? { bytes: new Uint8Array(await blob.arrayBuffer()) } : {}),
    });
  }
  const scenes =
    kind === '2d'
      ? (await listScenesForProject(db, projectId)).sort(
          (left, right) => left.position - right.position,
        )
      : [];
  const versions: LocalPieceVersionRecord[] =
    kind === '2d' ? [] : await listPieceVersions(db, ownerId, projectId);
  const records =
    kind === '2d'
      ? scenes.map((scene) => ({ schemaVersion: 1, data: scene.sceneJson }))
      : versions.map((version) => ({ schemaVersion: 1, data: version.payload }));
  const latest = versions.at(-1)?.payload ?? {};
  const measurement = measureLocalPiecePackageContent(records, mediaByteSizes);
  return { project, kind, records, mediaAssets, missingAssets, measurement, latest };
}

/** Measure package content from IndexedDB without constructing a ZIP archive. */
export async function measureLocalPiecePackage(
  db: IDBDatabase,
  ownerId: string,
  projectId: string,
): Promise<LocalPiecePackageMeasurement> {
  const content = await loadLocalPieceContent(db, ownerId, projectId, { includeMediaBytes: false });
  return { ...content.measurement, missingAssets: content.missingAssets };
}

/** Builds any local-first piece kind for the explicit account-sync offer. */
export async function buildLocalPiecePackage(
  db: IDBDatabase,
  ownerId: string,
  projectId: string,
  options: { title?: string; description?: string } = {},
): Promise<LocalPiecePackageResult> {
  const content = await loadLocalPieceContent(db, ownerId, projectId, { includeMediaBytes: true });
  const { buildPiecePackage, parsePiecePackage } = await import('./piecePackage');
  const bytes = await buildPiecePackage({
    kind: content.kind,
    title: options.title ?? content.project.title,
    description: options.description ?? content.project.description ?? '',
    visibilityIntent: 'private',
    appVersion: 'augmentrart-local-sync',
    records: content.records,
    mediaAssets: content.mediaAssets as Array<{
      sourceAssetId: string;
      filename: string;
      altText: string;
      mimeType: string;
      bytes: Uint8Array;
    }>,
    source:
      content.kind === 'generated'
        ? { engine: content.latest.engine ?? 'svg', code: content.latest.source ?? '' }
        : content.kind === '3d'
          ? { renderer: content.latest.renderer ?? null }
          : null,
    ink:
      content.kind === 'generated'
        ? ((content.latest.ink as Record<string, unknown>) ?? null)
        : null,
    sonic:
      content.kind === 'generated'
        ? ((content.latest.sonic as Record<string, unknown>) ?? null)
        : null,
    capabilities:
      content.kind === 'generated'
        ? ((content.latest.capabilities as Record<string, unknown>) ?? {})
        : null,
  });
  await parsePiecePackage(bytes);
  return { bytes, missingAssets: content.missingAssets, ...content.measurement };
}

/**
 * Build and checksum-verify a single local 2D piece without mutating
 * IndexedDB. `descriptionOverride` (issue #942) lets a caller supply a
 * description for the outgoing package.
 */
export async function buildLocal2dPiecePackage(
  db: IDBDatabase,
  ownerId: string,
  projectId: string,
  packageModule?: LocalPiecePackageModule,
  descriptionOverride?: string,
  titleOverride?: string,
): Promise<LocalPiecePackageResult> {
  const content = await loadLocalPieceContent(db, ownerId, projectId, {
    includeMediaBytes: true,
    kind: '2d',
  });
  const { buildPiecePackage, parsePiecePackage } =
    packageModule ?? (await loadPiecePackageModule());
  const bytes = await buildPiecePackage({
    kind: '2d',
    title: titleOverride ?? content.project.title,
    description: descriptionOverride ?? content.project.description ?? '',
    appVersion: 'local-first-2d',
    records: content.records,
    mediaAssets: content.mediaAssets as Array<{
      sourceAssetId?: string;
      filename: string;
      altText: string;
      mimeType: string;
      bytes: Uint8Array;
    }>,
  });
  await parsePiecePackage(bytes);
  return {
    bytes,
    missingAssets: content.missingAssets,
    ...content.measurement,
  };
}
