# Generated by Django 6.1 on 2026-08-16 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='Untitled animation', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('allow_public_remix', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('scene_json', models.JSONField()),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('ai_create', 'AI create'), ('ai_edit', 'AI edit'), ('restore', 'Restore'), ('fork', 'Fork')], max_length=20)),
                ('change_label', models.CharField(blank=True, default='', max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scene_versions', to=settings.AUTH_USER_MODEL)),
                ('fork_source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='scenes.sceneversion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scenes.sceneversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scenes.project')),
            ],
            options={
                'ordering': ['project', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_projects', to='scenes.sceneversion'),
        ),
        migrations.AddConstraint(
            model_name='sceneversion',
            constraint=models.UniqueConstraint(fields=('project', 'sequence'), name='unique_sequence_per_project'),
        ),
        migrations.AddConstraint(
            model_name='sceneversion',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='sequence_gte_1'),
        ),
    ]
