# Generated by Django 6.1 on 2026-08-16 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0003_projectactivity_editsessiondraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForkProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fork_provenance', to='scenes.project')),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forks_made', to='scenes.project')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forks_made', to='scenes.sceneversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('project', models.F('source_project')), _negated=True), name='fork_provenance_project_differs_from_source')],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('built_in', 'Built-in'), ('private', 'Private')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('scene_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_sourced', to='scenes.sceneversion')),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('source_type', 'built_in')), models.Q(('owner__isnull', False), ('source_type', 'private')), _connector='OR'), name='builtin_ownerless_private_owned')],
            },
        ),
    ]
