# Generated by Django 6.1 on 2026-08-16 07:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0006_alter_project_options_alter_project_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
