# Generated by Django 6.1 on 2026-08-16 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0007_alter_project_options_alter_project_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creation_request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='export_attribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_choice',
            field=models.CharField(blank=True, default='auto', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('owner', 'creation_request_id'), name='unique_creation_request_per_owner'),
        ),
    ]
