# Generated by Django 6.1 on 2026-08-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0010_seed_builtin_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsessiondraft',
            name='client_seq',
            field=models.BigIntegerField(default=0),
        ),
    ]
