# Generated by Django 6.1 on 2026-08-18 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0011_editsessiondraft_client_seq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneversion',
            name='ai_request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sceneversion',
            constraint=models.UniqueConstraint(condition=models.Q(('ai_request_id__isnull', False)), fields=('project', 'ai_request_id'), name='unique_ai_request_id_per_project'),
        ),
    ]
