# Generated by Django 6.1 on 2026-08-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0014_project_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allow_public_remix',
            field=models.BooleanField(default=True),
        ),
    ]
