# Generated by Django 6.1 on 2026-08-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0016_mistralcredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_choice',
        ),
    ]
