# Generated by Django 6.1 on 2026-08-29 05:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0017_remove_project_thumbnail_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project3D',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='Untitled 3D scene', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects_3d',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneVersion3D',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('sequence', models.PositiveIntegerField()),
                ('scene_json', models.JSONField()),
                (
                    'origin',
                    models.CharField(
                        choices=[('manual', 'Manual')], default='manual', max_length=20
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_scene_versions_3d',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='scenes.project3d',
                    ),
                ),
            ],
            options={
                'ordering': ['project', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='project3d',
            name='current_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='current_for_projects_3d',
                to='scenes.sceneversion3d',
            ),
        ),
        migrations.AddConstraint(
            model_name='sceneversion3d',
            constraint=models.UniqueConstraint(
                fields=('project', 'sequence'), name='unique_sequence_per_project_3d'
            ),
        ),
        migrations.AddConstraint(
            model_name='sceneversion3d',
            constraint=models.CheckConstraint(
                condition=models.Q(('sequence__gte', 1)), name='sequence_3d_gte_1'
            ),
        ),
    ]
