# Generated by Django 6.1 on 2026-08-29 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0018_project3d_sceneversion3d_project3d_current_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneversion3d',
            name='ai_request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sceneversion3d',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai_create', 'AI create'), ('ai_edit', 'AI edit')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='sceneversion3d',
            constraint=models.UniqueConstraint(condition=models.Q(('ai_request_id__isnull', False)), fields=('project', 'ai_request_id'), name='unique_ai_request_id_per_project_3d'),
        ),
    ]
