# Generated by Django 6.1 on 2026-09-01 23:56

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0024_project3d_published_at_project3d_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='Untitled art piece', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('prompt', models.TextField(max_length=4000)),
                ('engine', models.CharField(choices=[('canvas2d', 'Canvas2D'), ('svg', 'SVG'), ('threejs', 'Three.js'), ('aframe', 'A-Frame')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_pieces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ArtPieceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('source', models.TextField(max_length=1000000)),
                ('capabilities', models.JSONField(default=dict)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scenes.artpiece')),
            ],
            options={
                'ordering': ['piece', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ArtPieceThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
                ('content_type', models.CharField(default='image/png', max_length=50)),
                ('width', models.PositiveIntegerField(default=320)),
                ('height', models.PositiveIntegerField(default=240)),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='scenes.artpieceversion')),
            ],
        ),
        migrations.AddField(
            model_name='artpiece',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_pieces', to='scenes.artpieceversion'),
        ),
        migrations.AddConstraint(
            model_name='artpieceversion',
            constraint=models.UniqueConstraint(fields=('piece', 'sequence'), name='unique_art_piece_sequence'),
        ),
        migrations.AddConstraint(
            model_name='artpieceversion',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='art_piece_sequence_gte_1'),
        ),
        migrations.AddIndex(
            model_name='artpiece',
            index=models.Index(fields=['status', '-published_at', '-id'], name='art_piece_public_idx'),
        ),
    ]
