# Generated by Django 6.1 on 2026-09-06 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0034_session_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('project', '2D project'), ('project3d', '3D project')], max_length=20)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('edit_patch', 'Edit (patch)')], max_length=20)),
                ('scope', models.CharField(choices=[('whole_scene', 'Whole scene'), ('selection', 'Selection')], default='whole_scene', max_length=20)),
                ('selected_target_ids', models.JSONField(blank=True, default=list)),
                ('prompt', models.TextField()),
                ('vendor', models.CharField(default='mistral', max_length=32)),
                ('model_id', models.CharField(blank=True, default='', max_length=100)),
                ('persona_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('awaiting_review', 'Awaiting review'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('expired', 'Expired')], default='running', max_length=20)),
                ('base_version_id', models.PositiveIntegerField(blank=True, null=True)),
                ('input_digest', models.CharField(max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('repairs', models.PositiveIntegerField(default=0)),
                ('candidate_scene_json', models.JSONField(blank=True, null=True)),
                ('candidate_patch', models.JSONField(blank=True, null=True)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('plan_summary', models.TextField(blank=True, default='')),
                ('validation_summary', models.TextField(blank=True, default='')),
                ('error_reason', models.CharField(blank=True, default='', max_length=64)),
                ('usage_prompt_tokens', models.PositiveIntegerField(default=0)),
                ('usage_completion_tokens', models.PositiveIntegerField(default=0)),
                ('usage_cost_usd', models.FloatField(default=0.0)),
                ('charged', models.BooleanField(default=False)),
                ('accepted_version_id', models.PositiveIntegerField(blank=True, null=True)),
                ('advance_lease_token', models.UUIDField(blank=True, null=True)),
                ('advance_lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('start_request_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='scenes.project')),
                ('project3d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='scenes.project3d')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='ai_run_owner_recent_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('start_request_id__isnull', False)), fields=('owner', 'start_request_id'), name='unique_ai_run_start_request_id_per_owner')],
            },
        ),
    ]
