# Generated by Django 6.1 on 2026-09-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0040_trigger_scene_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cloud_storage_bytes',
            field=models.PositiveBigIntegerField(default=52428800),
        ),
        migrations.AddField(
            model_name='plan',
            name='cloud_storage_files',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cloud_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CloudBackupProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_backup', to='scenes.project')),
            ],
        ),
        migrations.CreateModel(
            name='CloudBackupManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('checksum', models.CharField(max_length=128)),
                ('manifest', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='scenes.cloudbackupproject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('backup', 'revision'), name='unique_cloud_manifest_revision'), models.UniqueConstraint(fields=('backup', 'idempotency_key'), name='unique_cloud_manifest_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='CloudBackupBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.UUIDField()),
                ('checksum', models.CharField(max_length=128)),
                ('mime_type', models.CharField(max_length=128)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('data', models.BinaryField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blobs', to='scenes.cloudbackupproject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('backup', 'asset_id'), name='unique_cloud_blob_asset'), models.UniqueConstraint(fields=('backup', 'idempotency_key'), name='unique_cloud_blob_idempotency')],
            },
        ),
    ]
