# Generated by Django 6.1 on 2026-09-13 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0051_seed_entitlement_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('handle', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('bio', models.TextField(blank=True, default='', max_length=1000)),
                ('website_url', models.URLField(blank=True, default='', max_length=300)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('profile_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_public', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='public_profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
