# Generated by Django 6.1 on 2026-09-13 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0055_seed_cloud_retention_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('vendor', models.CharField(max_length=32)),
                ('model_slug', models.CharField(max_length=200)),
                ('display_label', models.CharField(max_length=200)),
                ('task_kinds', models.JSONField(default=list)),
                ('agentic_supported', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'updated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['vendor', 'model_slug'],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('active', True)),
                        fields=('vendor', 'model_slug'),
                        name='unique_active_ai_provider_model',
                    )
                ],
            },
        ),
    ]
