# Generated by Django 6.1 on 2026-09-13 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0057_seed_ai_provider_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSyncSignupConsent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('sync_enabled', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                (
                    'owner',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cloud_sync_consent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
