# Generated by Django 6.1 on 2026-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0058_cloud_sync_signup_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cloud_snapshot_archive_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='cloud_snapshot_cadence_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
