# Generated by Django 6.1 on 2026-09-14 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0060_seed_snapshot_cadence_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneversion3d',
            name='source_project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='converted_3d_versions',
                to='scenes.project',
            ),
        ),
        migrations.AddField(
            model_name='sceneversion3d',
            name='source_version_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sceneversion3d',
            name='origin',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual'),
                    ('ai_create', 'AI create'),
                    ('ai_edit', 'AI edit'),
                    ('converted_from_2d', 'Converted from 2D'),
                ],
                default='manual',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='SceneConversionRun',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('source_version_id', models.PositiveIntegerField()),
                ('prompt', models.TextField(blank=True, default='')),
                ('vendor', models.CharField(default='mistral', max_length=32)),
                ('model_id', models.CharField(blank=True, default='', max_length=100)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('running', 'Running'),
                            ('awaiting_review', 'Awaiting review'),
                            ('accepted', 'Accepted'),
                            ('cancelled', 'Cancelled'),
                            ('failed', 'Failed'),
                            ('expired', 'Expired'),
                        ],
                        default='running',
                        max_length=20,
                    ),
                ),
                ('input_digest', models.CharField(max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('repairs', models.PositiveIntegerField(default=0)),
                ('candidate_scene_json', models.JSONField(blank=True, null=True)),
                ('unsupported_shape_types', models.JSONField(blank=True, default=list)),
                ('plan_summary', models.TextField(blank=True, default='')),
                ('validation_summary', models.TextField(blank=True, default='')),
                ('error_reason', models.CharField(blank=True, default='', max_length=64)),
                ('usage_prompt_tokens', models.PositiveIntegerField(default=0)),
                ('usage_completion_tokens', models.PositiveIntegerField(default=0)),
                ('usage_cost_usd', models.FloatField(default=0.0)),
                ('charged', models.BooleanField(default=False)),
                ('accepted_project3d_id', models.PositiveIntegerField(blank=True, null=True)),
                ('accepted_version_id', models.PositiveIntegerField(blank=True, null=True)),
                ('advance_lease_token', models.UUIDField(blank=True, null=True)),
                ('advance_lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('start_request_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scene_conversion_runs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'source_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scene_conversion_runs',
                        to='scenes.project',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['owner', '-created_at'], name='scene_conv_owner_recent_idx'
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('start_request_id__isnull', False)),
                        fields=('owner', 'start_request_id'),
                        name='unique_scene_conversion_run_start_request_id_per_owner',
                    )
                ],
            },
        ),
    ]
