# Generated by Django 6.1 on 2026-09-15 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0062_seed_convert_3d_feature_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncMutationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_id",
                    models.UUIDField(),
                ),
                (
                    "scene_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("client_sequence", models.PositiveBigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("scene", "Scene"),
                            ("metadata", "Metadata"),
                            ("media-reference", "Media reference"),
                        ],
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField()),
                ("payload_checksum", models.CharField(max_length=64)),
                ("schema_version", models.PositiveIntegerField()),
                ("dependency_operation_ids", models.JSONField(blank=True, default=list)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_mutation_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_mutation_receipts",
                        to="scenes.project",
                    ),
                ),
            ],
            options={
                "ordering": ["client_sequence", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "project", "client_sequence"],
                        name="sync_receipt_owner_proj_seq",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "operation_id"),
                        name="unique_sync_operation_per_owner",
                    ),
                    models.UniqueConstraint(
                        fields=("owner", "project", "client_sequence"),
                        name="unique_sync_sequence_per_project_owner",
                    ),
                ],
            },
        ),
    ]
