# Generated by Django 6.1 on 2026-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0074_global_site_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistralmodelpreference',
            name='vendor',
            field=models.CharField(db_default='mistral', default='mistral', max_length=32),
        ),
    ]
