# Generated by Django 6.1 on 2026-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0075_alter_mistralmodelpreference_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistralmodelpreference',
            name='vendor',
            field=models.CharField(
                blank=True, db_default='mistral', default='mistral', max_length=32, null=True
            ),
        ),
    ]
