# Generated by Django 6.1 on 2026-09-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0077_non_destructive_schema_bridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='seo_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project3d',
            name='seo_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
