# Generated by Django 6.1 on 2026-09-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0078_project_content_seo_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='engine',
            field=models.CharField(choices=[('canvas2d', 'Canvas 2D'), ('svg', 'SVG'), ('p5js', 'p5.js'), ('c2js', 'C2.js'), ('c2js-interactive', 'C2.js Interactive'), ('threejs', 'Three.js'), ('aframe', 'A-Frame')], max_length=20),
        ),
    ]
