# Generated by Django 6.1 on 2026-09-21 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0084_airun_auto_retry_enabled_airun_criterion_results_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPieceRefineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(max_length=4000)),
                ('target_references', models.JSONField(blank=True, default=list)),
                ('plan', models.JSONField(default=dict)),
                ('auto_retry_enabled', models.BooleanField(default=False)),
                ('max_retries', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('accepted', 'Accepted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('repairs', models.PositiveSmallIntegerField(default=0)),
                ('edits', models.JSONField(blank=True, default=list)),
                ('attempt_results', models.JSONField(blank=True, default=list)),
                ('candidate_source', models.TextField(blank=True, default='')),
                ('validation_summary', models.TextField(blank=True, default='')),
                ('error_reason', models.CharField(blank=True, default='', max_length=64)),
                ('usage_prompt_tokens', models.PositiveIntegerField(default=0)),
                ('usage_completion_tokens', models.PositiveIntegerField(default=0)),
                ('usage_cost_usd', models.FloatField(default=0.0)),
                ('charged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refine_runs', to='scenes.artpieceversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_piece_refine_runs', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refine_runs', to='scenes.artpiece')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
