# Generated by Django 5.2.6 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0089_database_defaults_for_shared_palettes"),
    ]

    operations = [
        migrations.AddField(
            model_name="artpieceversion",
            name="camera_placement",
            field=models.CharField(
                blank=True,
                choices=[("overlay", "Overlay"), ("background", "Background")],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="artpieceversion",
            constraint=models.CheckConstraint(
                condition=models.Q(camera_placement__isnull=True)
                | models.Q(camera_placement__in=["overlay", "background"]),
                name="art_piece_camera_placement_valid",
            ),
        ),
    ]
