# Generated by Django 6.1 on 2026-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0095_aiprovidermodel_native_schema_db_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='airun',
            name='assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='airun',
            name='scope',
            field=models.CharField(choices=[('whole_scene', 'Whole scene'), ('selection', 'Selection'), ('add_layer', 'Add asset layer')], default='whole_scene', max_length=20),
        ),
    ]
