# Generated by Django 5.2 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenes", "0100_cloudbackupproject_account_inherited"),
    ]

    operations = [
        migrations.AddField(
            model_name="pieceintakeasset",
            name="source_asset_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="pieceintakeasset",
            index=models.Index(
                fields=["piece_public_id", "source_asset_id"],
                name="piece_asset_public_source_idx",
            ),
        ),
    ]
