# Generated by Django 5.2 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("scenes", "0103_collection_comments_enabled_collectioncomment")]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="cover_asset_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="cover_piece_kind",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="collection",
            name="cover_piece_public_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
