# Generated by Django 6.1 on 2026-09-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0106_seed_unpublish_retention_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsyncpreference',
            name='consent_source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
