# Generated by Django 6.1 on 2026-10-02 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _remove_3d_activity_on_rollback(apps, schema_editor):
    """Drop rows from the family being removed before restoring the 2D-only FK."""
    ProjectActivity = apps.get_model("scenes", "ProjectActivity")
    ProjectActivity.objects.using(schema_editor.connection.alias).filter(
        project3d__isnull=False
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0111_airun_intent_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='project3d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='scenes.project3d'),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='scenes.project'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['project3d', '-created_at', '-id'], name='sc_pa_p3d_created_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectactivity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('project3d__isnull', True), ('project__isnull', False)), models.Q(('project3d__isnull', False), ('project__isnull', True)), _connector='OR'), name='sc_pa_exactly_one_family'),
        ),
        migrations.RunPython(migrations.RunPython.noop, _remove_3d_activity_on_rollback),
    ]
