# Generated by Django 6.1 on 2026-10-02 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _remove_art_piece_activity_on_rollback(apps, schema_editor):
    """Drop rows from the family being removed before restoring two-way schema."""
    ProjectActivity = apps.get_model("scenes", "ProjectActivity")
    ProjectActivity.objects.using(schema_editor.connection.alias).filter(
        art_piece__isnull=False
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0112_projectactivity_project3d_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectactivity',
            name='sc_pa_exactly_one_family',
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='art_piece',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='activity',
                to='scenes.artpiece',
            ),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(
                fields=['art_piece', '-created_at', '-id'], name='sc_pa_piece_created_id_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='projectactivity',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('project3d__isnull', True),
                        ('project__isnull', False),
                        ('art_piece__isnull', True),
                    ),
                    models.Q(
                        ('project3d__isnull', False),
                        ('project__isnull', True),
                        ('art_piece__isnull', True),
                    ),
                    models.Q(
                        ('project3d__isnull', True),
                        ('project__isnull', True),
                        ('art_piece__isnull', False),
                    ),
                    _connector='OR',
                ),
                name='sc_pa_exactly_one_family',
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            _remove_art_piece_activity_on_rollback,
        ),
    ]
