# Generated by Django 6.1 on 2026-10-04 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0113_remove_projectactivity_sc_pa_exactly_one_family_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPToolAuditEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool_name', models.CharField(max_length=80)),
                ('client_id', models.CharField(blank=True, max_length=200, null=True)),
                ('client_ip_fingerprint', models.CharField(max_length=64)),
                (
                    'outcome',
                    models.CharField(
                        choices=[
                            ('success', 'Success'),
                            ('error', 'Error'),
                            ('rate_limited', 'Rate limited'),
                        ],
                        max_length=16,
                    ),
                ),
                ('duration_ms', models.PositiveIntegerField()),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='mcp_tool_audit_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['user', '-created_at'], name='scenes_mcpt_user_id_4f8611_idx'
                    )
                ],
            },
        ),
    ]
